### ISSUE TITLE
Unable to start the container

### ISSUE THREAD

**Issue by red-avtovo** [axllent/alpine-dropbox#3]
Once I start the container
```
docker run -d \
--name dropbox \
--restart=unless-stopped \
-v data:/dbox/Dropbox \
-v config:/dbox/.dropbox \
axllent/alpine-dropbox
```

I get the error:
```
Installed Dropbox version: 107.4.443
dropbox: locating interpreter
dropbox: logging to /tmp/dropbox-antifreeze-oFRnEc
dropbox: initializing
dropbox: initializing python 3.7.9
dropbox: setting program path '/dbox/.dropbox-dist/dropbox-lnx.x86_64-107.4.443/dropbox'
dropbox: setting python path '/dbox/.dropbox-dist/dropbox-lnx.x86_64-107.4.443:/dbox/.dropbox-dist/dropbox-lnx.x86_64-107.4.443/python-packages.zip'
dropbox: python initialized
dropbox: running dropbox
dropbox: setting args
dropbox: enabling allocator metrics
ImportError: libstdc++.so.6: cannot open shared object file: No such file or directory
!! dropbox: fatal python exception:
['ImportError: libstdc++.so.6: cannot open shared object file: No such file or directory\n'] (error 3)
Dropbox isn't running!
Aborted (core dumped)
```

I believe that because the repo is stale for quite a while

**Comment by axllent** [comment]
Hi @red-avtovo . To be honest I haven't ever had much long-term luck with this image. It was built on top of Alpine Linux to keep the size down, however Alpine itself doesn't use glibc (which Dropbox requires), so it the image uses `frolvlad/alpine-glibc` which is a port of glibc on Alpine. About a year ago I personally switched to a debian-based dropbox image (`oddlid/dropbox`) which seems to be stable enough (also has the odd crash though).

To see if it helps.,I have just created a new image of `axllent/alpine-dropbox` which uses the latest upstream `frolvlad/alpine-glibc`. If it does solver the issue, then great, if it doesn't then I would suggest switching to another docker image such as `oddlid/dropbox`. Please report back once you have tested it to let me know if the new build fixes the crash for you? Thanks.

**Comment by red-avtovo** [comment]
Thanks for your reply. Didn't expect to get it so soon :smile: 
I'm playing right now with [this](https://hub.docker.com/r/bnutz/min-ubuntu-dropbox/) image and it looks very promising, but I will still try the one you've mentioned above.
I tried all Alpine dropbox images which I could find and I failed to use any of them due to major changes from the dropbox binary. Not mentioning the fact that all images are at least 2y old.

**Comment by axllent** [comment]
The whole point of using Alpine was the size, however considering one had to use a modified image to start with _and_ after you install python etc, it really didn't make it _that_ much smaller. I guess the idea was right, but the outcome wasn't too hot ;-)

OK, no problem, moving onto another image is probably the right option for you. I'll probably remove this repo and docker image then, as it isn't used (by me), so it's not actively updated (although Dropbox itself is downloaded fresh on every run).

**Comment by red-avtovo** [comment]
It's sad to admit, that maybe it is the right decision. I would suggest though to mention the current issue in "Good-Bye README"

Regarding the image you've recommended: it also doesn't work :cry: 
After running a fast check-up script:
```
docker run -it --rm --name dropbox -v $HOME/Documents/data:/dbox/Dropbox -v $HOME/Documents/config:/dbox/.dropbox oddlid/dropbox
```

I get:
```
This computer is now linked to Dropbox. Welcome Storage
Couldn't start Dropbox.
This is usually because of a permissions error. Storing your home folder on a network share can also cause an error.

Get more help at https://www.dropbox.com/c/help/permissions_error

Please contact Dropbox support with the following info for help:

/tmp/dropbox_errora4ccnb1a.txt
```

PS:
I would also recommend mentioning the only (as of now) working image which could be easily checked in under 1 minute by running this script:
```
docker run -it --rm --name dropbox -v $HOME/Documents/data:/dbox/Dropbox -v $HOME/Documents/config:/dbox/.dropbox bnutz/min-ubuntu-dropbox
```

**Comment by red-avtovo** [comment]
Funny thing, I just noticed that it is in fact a fork from your repository

**Comment by axllent** [comment]
Ha, that is funny. I'm guessing he forked it and decided that Ubuntu was a better fit than Alpine. I'm also guessing that the reason you get issues with `oddlid/dropbox` is that your user ID isn't 1000 (I think it's hardcoded to use 1000). 

Anyway, thanks for the feedback. I will update the README & retire this project as it's obviously not working (as it should).
